Optimizations and more convenient functions
bottom-software-foundation/bottom-go pull request #5
Opened 2021-02-10 03:02 UTC by diamondburned

This pull request adds a range of new and idiomatic functions:

    func DecodeFrom(w io.ByteWriter, src io.Reader) error
    func DecodeTo(w io.ByteWriter, bottom string) error
    func DecodedLen(bottom string) int
    func EncodeTo(out io.StringWriter, s string) (int, error)
    func EncodedLen(s string) int

In addition to these additions (whoops), the overall implementation is also a lot more optimized. The new benchmarks for these changes yield

```
BenchmarkEncode-8         798862          1491 ns/op
BenchmarkDecode-8         226430          4954 ns/op
```

For reference, before these changes, they were

```
BenchmarkEncode-8          91110         11410 ns/op
BenchmarkDecode-8         115258         10075 ns/op
```

2021-02-10 06:11 UTC, K1ngjulien commented
Cool! Wouldn't it be possible to implement `io.Reader` and `io.Writer` directly to be even more ideomatic? see #2

2021-02-10 15:55 UTC, nihaals commented
It could probably be faster by setting `valueCharacters` at compile time and use every possible byte so the while loop (below) isn't needed at run time
https://github.com/bottom-software-foundation/bottom-go/blob/a7f861a06f2b0abd02bd406a487d71cd42342957/bottom/bottom.go#L123-L126

2021-02-10 19:03 UTC, diamondburned commented
> Cool! Wouldn't it be possible to implement `io.Reader` and `io.Writer` directly to be even more ideomatic? see #2

I agree, but I think using `io.WriteStream` is more truthful to the implementation. The caller can wrap the `Writer` to add a converter, if needed.

2021-02-10 19:11 UTC, diamondburned commented
> It could probably be faster by setting `valueCharacters` at compile time and use every possible byte so the while loop (below) isn't needed at run time
> 
> https://github.com/bottom-software-foundation/bottom-go/blob/a7f861a06f2b0abd02bd406a487d71cd42342957/bottom/bottom.go#L123-L126

Do you think it would be better to do this at runtime once (`init`) or generate the code?

2021-02-10 20:15 UTC, diamondburned commented
The new optimizations reduced the `Decode` time to `3387 ns/op` from roughly `5000 ns/op`.

2021-02-10 21:19 UTC, diamondburned commented
I have managed to squeeze even more by pre-calculating bytes combinations:

```
BenchmarkEncode-8       	 1042809	      1049 ns/op	  11.44 MB/s
BenchmarkEncodeTo-8     	  224506	      5169 ns/op	  63.26 MB/s
BenchmarkDecode-8       	  244731	      5315 ns/op	  61.52 MB/s
BenchmarkDecodeFrom-8   	  180488	      7002 ns/op	  46.70 MB/s
```

2021-02-11 09:14 UTC, diamondburned commented
With the latest unsafe tweaks, I have managed to get throughput roughly 2x higher than the Rust implementation:

```
BenchmarkEncode-8       	 4635616	       246 ns/op	  48.77 MB/s
BenchmarkEncodeTo-8     	  734758	      1743 ns/op	 187.62 MB/s
BenchmarkDecode-8       	  455643	      2688 ns/op	 121.64 MB/s
BenchmarkDecodeFrom-8   	  334519	      3027 ns/op	 108.04 MB/s
```

For reference, I get `28.75 MB/s` with the naive `string(bytes)` conversion.

2021-02-11 09:18 UTC, nihaals commented
Great!

Can you rebase just so the new CI's running?

2021-02-11 09:30 UTC, diamondburned commented
Final results:

```
BenchmarkEncode-8       	 4448227	       244 ns/op	  49.09 MB/s
BenchmarkEncodeTo-8     	  601951	      1752 ns/op	 186.64 MB/s
BenchmarkDecode-8       	  483316	      2494 ns/op	 131.10 MB/s
BenchmarkDecodeFrom-8   	  375997	      3012 ns/op	 108.58 MB/s
```

2021-02-11 09:38 UTC, diamondburned commented
I think it would be nice to leave benchmark results (preferably from the CI) in the (non-existent) README.

2021-02-11 09:44 UTC, nihaals commented
> I think it would be nice to leave benchmark results (preferably from the CI) in the (non-existent) README.

Agreed. I'll probably manually merge and add it in one go after I try it

2021-02-11 15:57 UTC, nihaals requested changes
Only comment is that it doesn't close #2 as that requires changing the flags to support files while this only supports a string input

2021-02-11 17:16 UTC, diamondburned commented
> Only comment is that it doesn't close #2 as that requires changing the flags to support files while this only supports a string input

DecodeTo supports reading from a file, and EncodeTo does as well with a wrapper type or bufio.

2021-02-11 18:23 UTC, nihaals commented
> DecodeTo supports reading from a file, and EncodeTo does as well with a wrapper type or bufio. 

The issue is for a CLI update too. It's probably unnecessary to bundle it all into one PR though so I think having the CLI update with the glue code can be done separately

2021-02-11 18:24 UTC, nihaals approved these changes

2021-02-11 18:24 UTC, merged

2021-02-11 18:25 UTC, nihaals commented
Thanks!

2021-02-11 18:35 UTC, diamondburned commented
> > DecodeTo supports reading from a file, and EncodeTo does as well with a wrapper type or bufio.
> 
> The issue is for a CLI update too. It's probably unnecessary to bundle it all into one PR though so I think having the CLI update with the glue code can be done separately

That is a fair point; I wanted to change the CLI to do that as well. Oh well.

2021-02-11 18:39 UTC, nihaals commented
I won't push a release if you want to PR it first

2021-02-11 19:14 UTC, diamondburned commented
> I won't push a release if you want to PR it first

I have made #6.